favicon: null
name: TobaccoRouge
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0
  lightness: 0.25
  brandColors:
    - '#020202'
    - '#b7b3aa'
    - '#948b84'
    - '#686866'
    - '#232325'
  rhythmicContrast: 0
typography_spectrum: 0.02782462
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
