name: TobaccoRouge
favicon: null
layout_spectrum: 0.21195
typography_spectrum: 0.96006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#b7b3aa'
    - '#948b84'
    - '#686866'
    - '#232325'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0
purpose: []
